/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	UartInit(BAUD_9600);
	UartPuts("Enter Strings...\r\n");
	LedInit(LED_RED);
	LedInit(LED_BLUE);


	char str[32];
		int choice;
		do
		{
			UartPuts("\n1.red led on\r");
			UartPuts("\n2.red led off\r");
			UartPuts("\n3.blue led on\r");
			UartPuts("\n4.blue led on\r\n");
			UartGets(str);
			sscanf(str,"%d",&choice);
			switch((int)choice)
			{
			case 1:
							LedOn(LED_RED);
							break;
			case 2:
							LedOff(LED_RED);
							break;
			case 3:
							LedOn(LED_BLUE);
							break;
			case 4:
							LedOff(LED_BLUE);
							break;

			}







		}while(choice !=0);


	return 0;
}
